imageScanner:
  configs:
    CLAIR_ADDR: clair.devtroncd:6060
    CLIENT_ID: client-2
    NATS_SERVER_HOST: nats://devtron-nats.devtroncd:4222
    PG_ADDR: postgresql-postgresql.devtroncd
    PG_DATABASE: orchestrator
    PG_LOG_QUERY: "false"
    PG_PORT: "5432"
    PG_USER: postgres
  # secrets:
  #   PG_PASSWORD: "devtron"
  image: "quay.io/devtron/image-scanner:b278f42b-334-10141"
  imagePullPolicy: IfNotPresent
  resources: {}

guard:
  image: "quay.io/devtron/guard:62058d7c-122-2192"
  imagePullPolicy: IfNotPresent
  replicaCount: 2

clair:
  enabled: false
  fullnameOverride: clair