imageScanner:
  configs:
    CLAIR_ADDR: clair.devtroncd:6060
    CLIENT_ID: client-2
    NATS_SERVER_HOST: nats://devtron-nats.devtroncd:4222
    PG_ADDR: postgresql-postgresql.devtroncd
    PG_DATABASE: orchestrator
    PG_LOG_QUERY: "false"
    PG_PORT: "5432"
    PG_USER: postgres
  # secrets:
  #   PG_PASSWORD: "devtron"
  dbconfig:
    secretName: postgresql-postgresql
    keyName: postgresql-password
  image: "quay.io/devtron/test:b278f42b-4642-2957"
  imagePullPolicy: IfNotPresent
  resources: {}

clair:
  enabled: false
  fullnameOverride: clair
  extraEnv:
  - name: CLAIR_CONF
    value: /etc/clair/config.yaml
  - name: CLAIR_MODE
    value: combo
  - name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        key: postgresql-password
        name: postgresql-postgresql