apiVersion: v2
name: devtron-operator
appVersion: 0.6.0
description: Chart to configure and install Devtron. Devtron is a Kubernetes Orchestration system.
keywords:
  - Devtron
  - Kubernetes
  - Orchestration
  - K8s
  - Deployment
  - argo-cd
  - Hyperion
engine: gotpl
version: 0.22.125
sources:
  - https://github.com/devtron-labs/charts
dependencies:
- name: argo-cd
  version: "5.2.0"
  repository: https://argoproj.github.io/argo-helm
  condition: argo-cd.enabled
- name: security
  version: "0.x.x"
  repository: https://dheeth.github.io/charts
  condition: security.enabled
maintainers:
- email: prakarsh@devtron.ai
  name: Prakarsh
icon: https://s3-ap-southeast-1.amazonaws.com/devtron.ai/images/devtron-sqr-logo.png
home: https://devtron.ai
