{{- with .Values.guard }}
{{- $altNames := list ( printf "guard-service guard-service.devtroncd guard-service.devtroncd.svc guard-service.devtroncd.svc.cluster.local" ) -}}
{{- $ca := genCA "guard-ca" 3652 -}}
{{- $cert := genSignedCert "guard-service.devtroncd.svc" nil $altNames 3652 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: guard-secret
  labels:
    release: devtron
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-1"
type: Opaque
data:
  cert.pem: {{ $cert.Cert | b64enc }}
  key.pem: {{ $cert.Key | b64enc }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: grumpy
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "1"
webhooks:
  - name: grumpy.pipo02mix.org
    clientConfig:
      service:
        name: guard-service
        sideEffects: NoneOnDryRun
        admissionReviewVersions: ["v1", "v1beta1"]
        namespace: devtroncd
        path: "/validate"
      caBundle:
{{ $ca.Cert | b64enc | indent 8 }}
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
---
apiVersion: v1
kind: Service
metadata:
  name: guard-service
  labels:
    app: guard
    release: devtron
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: app
      protocol: TCP
      name: app
  selector:
    app: guard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guard
  labels:
    app: guard
    release: devtron
spec:
  selector:
    matchLabels:
      app: guard
      release: devtron
  replicas: {{ .replicaCount }}
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: guard
        release: devtron
    spec:
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
      containers:
        - name: guard
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          ports:
            - name: app
              containerPort: 8080
              protocol: TCP
          args:
            - -alsologtostderr
            - --log_dir=/
            - -v=10
            - --validator_url=http://devtron-service.devtroncd:80
            - 2>&1
          env:
            - name: CONFIG_HASH
              value: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
            - name: SECRET_HASH
              value: abaee17d930a742e0a3554336348fde8a2b20e23bbdabb29b4acb8ac393b5da9
            - name: DEVTRON_APP_NAME
              value: guard
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
{{- if .resources }}
          resources:
{{ toYaml .resources | indent 12 }}
{{- end }}
          volumeMounts:
            - mountPath: /tmp
              name: log-volume
            - name: guard-secret-vol
              mountPath: /etc/certs
      volumes:
        - emptyDir: {}
          name: log-volume
        - name: guard-secret-vol
          secret:
            secretName: guard-secret
  revisionHistoryLimit: 3
{{- end }}